# Generated by Django 3.1.3 on 2024-09-28 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=4, unique=True)),
                ('pname', models.CharField(max_length=20)),
                ('punitprice', models.PositiveIntegerField()),
                ('pdiscountrate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pcontent', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('image01', models.ImageField(upload_to='sales/image1/', verbose_name='업로드 이미지1')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_Product', to=settings.AUTH_USER_MODEL)),
                ('pcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.category')),
            ],
        ),
    ]
