# Generated by Django 3.1.3 on 2024-09-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20240928_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
