# Generated by Django 3.1.3 on 2024-09-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20240930_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
