# Generated by Django 3.1.3 on 2024-09-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20240930_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pcategories',
            new_name='pcategory',
        ),
    ]
